import { robotType } from './RobotList';
export const deities: robotType[] = [
    { name: 'Abhoth', velocity: 2, endurance: 7 },
    { name: 'Aiueb Gnshal', velocity: 4, endurance: 5 },
    { name: 'Aletheia', velocity: 1, endurance: 3 },
    { name: 'Azathoth', velocity: 8, endurance: 10 },
    { name: 'Azhorra-Tha', velocity: 5, endurance: 6 },
    { name: 'The Blackness from the Stars', velocity: 3, endurance: 4 },
    { name: 'The Cloud-Thing', velocity: 2, endurance: 9 },
    { name: "C'thalpa", velocity: 7, endurance: 2 },
    { name: 'Cxaxukluth', velocity: 1, endurance: 10 },
    { name: 'Daoloth', velocity: 6, endurance: 4 },
    { name: 'Darkness', velocity: 10, endurance: 3 },
    { name: "D'endrrah", velocity: 3, endurance: 8 },
    { name: 'Eihort', velocity: 7, endurance: 1 },
    { name: 'The Great Denier', velocity: 5, endurance: 7 },
    { name: 'The Light of Leng', velocity: 9, endurance: 5 },
    { name: 'The Mass of Nothingness', velocity: 4, endurance: 2 },
    { name: 'The Nameless Mass', velocity: 8, endurance: 6 },
    { name: 'The Mother of Darkness', velocity: 2, endurance: 3 },
    { name: 'The Crawling Mind', velocity: 10, endurance: 8 },
    { name: 'Nyarlathotep', velocity: 1, endurance: 9 },
    { name: 'Shub-Niggurath', velocity: 6, endurance: 10 },
    { name: 'Yig', velocity: 3, endurance: 1 },
    { name: 'Yog-Sothoth', velocity: 9, endurance: 4 },
    { name: 'Zhar', velocity: 4, endurance: 5 },
];
