import { RobotType } from './RobotList';
export const deities: RobotType[] = [
    {
        name: 'Abhoth',
        velocity: 2,
        endurance: 7,
        created_at: '1961-06-06',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Aiueb Gnshal',
        velocity: 4,
        endurance: 5,
        created_at: '1929-11-16',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Aletheia',
        velocity: 1,
        endurance: 3,
        created_at: '1922-07-27',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Azathoth',
        velocity: 8,
        endurance: 10,
        created_at: '1922-06-02',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Azhorra-Tha',
        velocity: 5,
        endurance: 6,
        created_at: '1928-03-11',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Blackness',
        velocity: 3,
        endurance: 4,
        created_at: '1953-09-23',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Cloud-Thing',
        velocity: 2,
        endurance: 9,
        created_at: '1962-07-27',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: "C'thalpa",
        velocity: 7,
        endurance: 2,
        created_at: '1938-07-20',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Cxaxukluth',
        velocity: 1,
        endurance: 10,
        created_at: '1944-09-15',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Daoloth',
        velocity: 6,
        endurance: 4,
        created_at: '1934-08-23',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Darkness',
        velocity: 10,
        endurance: 3,
        created_at: '1919-08-23',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: "D'endrrah",
        velocity: 3,
        endurance: 8,
        created_at: '1932-08-14',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'Eihort',
        velocity: 7,
        endurance: 1,
        created_at: '1943-09-19',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Great Denier',
        velocity: 5,
        endurance: 7,
        created_at: '1924-02-05',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Light of Leng',
        velocity: 9,
        endurance: 5,
        created_at: '1946-09-14',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Mass of Nothingness',
        velocity: 4,
        endurance: 2,
        created_at: '1924-12-01',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Nameless Mass',
        velocity: 8,
        endurance: 6,
        created_at: '1947-08-31',
        manufacturer: 'Robotentacle Inc.',
    },
    {
        name: 'The Mother of Darkness',
        velocity: 2,
        endurance: 3,
        created_at: '1940-06-29',
        manufacturer: 'Robotentacle Inc.',
    },
];
