export const phrases = [
    'Mysterious malfunctions reported at the robot factory last night!',
    'Some say they saw strange, glowing lights coming from the robot storage room.',
    'Robots behaving oddly? Could it be the influence of the ancient ones?',
    'Are the robots at the factory being controlled by forces beyond our understanding?',
    'Reports of robotic beings chanting in an unknown language at the factory.',
    'Unexplained power outages plaguing the robot assembly line.',
    'Robots seen walking through walls at the factory - is this the work of the Great Old Ones?',
    'The robot factory is becoming a hotbed of paranormal activity.',
    'Is the robot factory hiding secrets from another dimension?',
    'Robots disappearing and reappearing without explanation at the factory.',
    'The robot factory has become a portal to the unknown, according to some.',
    'Is the robot factory built on top of an ancient, forbidden city?',
    'Rumors of robots being possessed by malevolent entities at the factory.',
    'The robot factory is a gateway to the realms of madness, some say.',
    'Are the robots at the factory being controlled by an unseen hand?',
    'Mysterious symbols appearing on the robotic components at the factory.',
    'Workers at the robot factory claim to have seen ghostly apparitions.',
    'Is the robot factory hiding a secret cult devoted to the ancient ones?',
    'Reports of robots exhibiting superhuman strength at the factory.',
    'Could the robot factory be built on top of an ancient, cursed burial ground?',
];
